# See: https://gohugo.io/getting-started/configuration/#merge-configuration-from-themes
_merge = "deep"

favicon_mstilecolor = "#b91d47"

### BGN: Structured Data ###
  description = "YuÌ„gen Bard ğŸ» by áœŒáœ“áœƒáœ’ (Yuki ãƒ» é›ªäº®) / Yahuhanan Yukiya Sese Cuneta."
  keywords = ["Yugen Bard", "YuÌ„gen Bard", "å¹½ç„åŸéŠè©©äºº", "ìŒìœ ì‹œì¸", "å¹½ ç„ ìŒìœ  ì‹œì¸", "YourOnlyOne", "YourOnly.One", "Yahuhanan Yukiya Sese Cuneta", "Yuki", "YoHan", "Yo-Han",  "×™×”×•×—× ×Ÿ", "áœŒáœ“áœƒáœ’", "ì‚¬ìš”í•œ", "è¬é›ªçŸ¢ï¼ˆã‚†ãã‚„ï¼‰", "ìŠ¤ë…¸", "Seu-No", "SeuNo", "Snow", "Yohanan", "áœŒáœ“áœ‘áœˆáœˆáœ”", "áœŒáœ“áœ‘áœˆáœˆáœ•", "áœŒáœ‘áœ“áœ‘áœˆáœˆáœ”", "áœŒáœ‘áœ“áœ‘áœˆáœˆáœ•"] # Can be overriden per page
  images = ["https://rsc.youronly.one/img/y/Yugen_Bard-logo-01-1500x.webp"]
### END: Structured Data ###

### BGN: Theme Settings ###
  message = ""
  hideAutoMenu = false

  # Pagination options
  paginate = 12
  multipage = false

  # Dark mode
  darkMode = true
### END: Theme Settings ###

### BGN: Other Settings ###
  [semweb]
    datecreated = "2021-02-06"
    sameas = [
      "https://www.facebook.com/yugenbard",
      "https://c.im/@YourOnlyOne",
      "https://pixelfed.social/YourOnlyOne",
      "https://www.youtube.com/@YourOnlyOneOfcl",
      "https://www.facebook.com/YourOnly.ONE.ofcl"
    ]
### END: Other Settings ###
